# file generated by hatch-vcs
# fallback version for editable installs without git tags
from __future__ import annotations

__all__ = [
    "__commit_id__",
    "__version__",
    "__version_tuple__",
    "commit_id",
    "version",
    "version_tuple",
]

version: str
__version__: str
__version_tuple__: tuple[int | str, ...]
version_tuple: tuple[int | str, ...]
commit_id: str | None
__commit_id__: str | None

__version__ = '0.1.0'
version = __version__
__version_tuple__ = (0, 1, 0)
version_tuple = __version_tuple__
__commit_id__ = None
commit_id = __commit_id__
